SUBROUTINE MAT_INV(AMAT,A_INV,IPVT,N,LDA)       !YSUSE
IMPLICIT DOUBLE PRECISION (A-H,O-Z)
!
DIMENSION AMAT(LDA,*),	A_INV(LDA,*),IPVT(*)
DIMENSION B(N)
!
	A_INV(1:N,1:N) = 0.0 ;
	CALL DEC(N, LDA,AMAT,IPVT, IER); !LU-Factorization Routine IPVT(IORDER)
!
	DO L=1,N
		B = 0.0; B(L)= 1.0;CALL SOL(N, LDA,AMAT, B,IPVT);
		A_INV(1:N,L) = B(1:N)
	END DO
!
END SUBROUTINE MAT_INV